[package]
name = "aevyrn_cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
log.workspace = true
env_logger.workspace = true
aevyrn_core = { path = "../aevyrn_core" }
aevyrn_window = { path = "../aevyrn_window" }
aevyrn_runtime = { path = "../aevyrn_runtime" }
thiserror.workspace = true

[[bin]]
name = "aevyrn"
path = "src/main.rs"
